// LOCALHOST
POST http://localhost:5182/graphql
Content-Type: application/json

{
    "query": "query example($id: ID!) { author(id: $id) { firstName lastName books { name publicationYear publisher } } }",
    "variables": {
        "id": "6a231a61685f62fe5ca4f034"
    }
}
###
// PRODUCTION
###
POST https://cse341-personal-606w.onrender.com/graphql
Content-Type: application/json

{
    "query": "query example($id: ID!) { author(id: $id) { firstName lastName books { name publicationYear publisher } } }",
    "variables": {
        "id": "6a231a61685f62fe5ca4f034"
    }
}
###